import java.util.*;

public class DoQuest {
    private static final List<String> veryEasyQuests = Arrays.asList(
            "Drink a glass of water 💧",
                    "Take 3 deep breaths 🌬️",
                    "Stretch your arms for 10 seconds 🙆‍♂️",
                    "Open a window and take a fresh breath 🌤️",
                    "Smile at yourself in the mirror 😊",
                    "Write one word that describes your mood 🖊️",
                    "Sit quietly for 10 seconds 🧘",
                    "Touch your toes or try 👣",
                    "Look away from your screen for 20 seconds 👀",
                    "Take one slow breath in and out 🌬️",
                    "Yawn and stretch on purpose 🥱",
                    "Stand up for 15 seconds 🧍‍♂️",
                    "Pick up one object and put it in its place 📦",
                    "Close your eyes and imagine a happy memory 🌈",
                    "Say “thank you” out loud 🙏",
                    "Snap your fingers 10 times 🫰",
                    "Wiggle your toes or fingers for fun 🦶🖐️",
                    "Doodle a random shape ✏️",
                    "Tap your heart gently 3 times ❤️",
                    "Pet something soft (pillow, fabric, pet) 🐾",
                    "Blink slowly 3 times 🕊️",
                    "Hum a tune for 5 seconds 🎵",
                    "Whisper something kind to yourself 🗣️",
                    "High five the air 🙌",
                    "Tidy one tiny area (pen, cable, notebook) 🧹",
                    "Clap your hands three times 👏",
                    "Snap a photo of something nearby 📸",
                    "Pick your favorite color and name 3 things that have it 🎨",
                    "Say one positive word out loud (“Peace”, “Strong”, etc.) 🗣️",
                    "Make a silly face to yourself 😜",
                    "Flick a light switch on and off slowly 💡",
                    "Stack 3 small objects near you 🧱",
                    "Rub your hands together and feel the warmth 🔥",
                    "Close your eyes and count to 10 slowly 🔟",
                    "Whisper your name lovingly 💬",
                    "Write a single dot on paper and stare at it for 5 seconds ⚫",
                    "Find a smooth texture to touch 🎐",
                    "Tap your chest 5 times gently 🫀",
                    "Raise your arms and hold for 3 seconds ✨",
                    "Pretend to be a statue for 10 seconds 🗿",
                    "Write “I exist and I matter” on a note 📝",
                    "Choose a new favorite word today 🧠",
                    "Say “I’m okay” 3 times 🌼",
                    "Make a gentle sound (humming, sighing, tapping) 🎶",
                    "Close your eyes and imagine the wind 🍃",
                    "Touch something cold (cup, wall, etc.) ❄️",
                    "Pick an object and describe it with 3 words 🧸",
                    "Stand on one foot for 5 seconds 🦶",
                    "Look in the mirror and blink slowly 🪞",
                    "Tap a rhythm on your desk or lap 🥁");

    private static final List<String> easyQuests = Arrays.asList(
            "Write a one-sentence journal entry 📓",
                "Do 5 jumping jacks or squats 🏃‍♀️",
                "Set a 2-minute timer and breathe ⏱️",
                "Clean your desk or a small area 🪑",
                "Write one thing you’re grateful for 🙏",
                "Walk for 2 minutes 🚶",
                "Drink a full bottle of water 🍼",
                "Write one goal for tomorrow 🎯",
                "Avoid your phone for 10 minutes 📵",
                "Eat one fruit 🍎",
                "Make your bed 🛏️",
                "Water a plant 🌿",
                "Put on fresh clothes 👕",
                "Play your favorite song 🎶",
                "Do a 30-second dance 💃",
                "Light a candle or smell something calming 🕯️",
                "Look up at the sky for a moment ☁️",
                "Compliment someone or yourself 💬",
                "Sit in silence for 1 full minute 🧘‍♀️",
                "Drink something warm ☕",
                "Stretch your whole body for 30 seconds 🙆‍♀️",
                "Organize one folder (physical or digital) 🗂️",
                "Wash your face 🚿",
                "Read one quote or affirmation 📖",
                "Unsubscribe from one distracting app 🔕",
                "Write one thing you’re avoiding 🧭",
                "Do 10 gentle arm circles 🙆",
                "Drink water and sit still for one minute afterward 💧",
                "Write a quote that inspires you 📜",
                "Stand up and stretch your whole body for 45 seconds 🧘‍♂️",
                "Walk barefoot for a moment (indoors is okay) 🦶",
                "Sort your backpack or bag 🎒",
                "Lightly massage your shoulders 💆‍♀️",
                "Take 10 slow steps mindfully 🚶",
                "Put on a song and only listen (no multitasking) 🎧",
                "Write down what time you went to sleep yesterday 🕰️",
                "Name three emotions you've felt today 😐😃😟",
                "Write one thing you’ve improved in the past month 📈",
                "Put away three objects in your space 🧹",
                "Screenshot or write down something funny 😂",
                "Write a short thank-you message (can be unsent) 💌",
                "Try a power pose for 10 seconds 🦸‍♂️",
                "Eat something slowly and mindfully 🍓",
                "Write your name using your non-dominant hand ✍️",
                "Spend 1 minute noticing sounds around you 🔊",
                "Write one good decision you made today ✅",
                "Change one setting on your device for focus mode 🔕",
                "Let yourself do nothing for 60 seconds 🧘",
                "Take 3 photos of calming things 🌼📷",
                "Make up a motivational mantra and say it aloud 🧘‍♀️🗣️");

    private static final List<String> harderQuests = Arrays.asList(
            "Journal for 5+ minutes 📘",
                "Exercise or move for 10 minutes 💪",
                "Meditate for 5 minutes 🧘‍♂️",
                "Make a healthy meal or snack 🥗",
                "Write down 3 things you're grateful for 🙌",
                "Write about something you want to improve ✍️",
                "Declutter a drawer or shelf 🗃️",
                "Read 3+ pages of a book 📚",
                "Go offline for 30+ minutes 📴",
                "Write 3 things you’re proud of ✨",
                "Spend 10 minutes organizing your digital space 💻",
                "Do something kind for someone 💛",
                "Take a slow walk with no distractions 🚶‍♂️",
                "Reflect on your week in writing 📅",
                "Watch or listen to something educational 🎧",
                "Stretch every major body part 🧘",
                "Try a breathing technique (box breath, 4-7-8) 🌬️",
                "Speak kindly to yourself in the mirror 🪞",
                "Make a mini plan for tomorrow 📝",
                "Write a letter (to your future self, a friend, etc.) 💌",
                "Take a mindful shower or bath 🚿",
                "Clean up your phone’s home screen 📱",
                "Do a simple body scan meditation 🛌",
                "Sit in nature or with a plant for 5+ minutes 🌲",
                "Stay off social media until a set time 📵",
                "Cook a simple meal without rushing 🍲",
                "Reflect: What made you smile recently? ✨",
                "Watch a short motivational or educational video 🎥",
                "Identify and remove one digital distraction 🔐",
                "Do a 3-minute mindfulness breathing session 🌬️",
                "Reorganize your workspace or room corner 🛋️",
                "Plan tomorrow’s top 3 tasks 📋",
                "Do 15 minutes of intentional screen-free time ⏳",
                "Write a micro-story or poem 📖",
                "Wash your hands slowly and mindfully 💧",
                "Make a to-don’t list (things to avoid) 🧠",
                "Go outside and notice 5 things 🏞️",
                "Write a short letter to your past or future self ✉️",
                "Practice gratitude by listing 3 small wins today 🏆",
                "Stretch for 5 minutes with calming music 🎼",
                "Reflect on what you’re proud of this week 🪞",
                "Delete 5 unneeded items from your phone/computer 🗑️",
                "Practice saying “no” in writing or aloud ✋",
                "Set a personal intention for the day 🌅",
                "Research one healthy habit or idea 📘",
                "Walk without your phone for 5–10 minutes 🚶‍♀️",
                "Draw or color for 5+ minutes 🎨",
                "Write a “brain dump” of thoughts or stress 💭",
                "Clean your phone screen and case 📱🧼",
                "Create a mini calming routine (1–2 steps) 🧘‍♀️🕯️");

    public static List<String> get5QuestsByLevel(int level) {
        List<String> pool;

        if (level <= 3) {
            pool = new ArrayList<>(veryEasyQuests);
        } else if (level <= 6) {
            pool = new ArrayList<>(easyQuests);
        } else {
            pool = new ArrayList<>(harderQuests);
        }

        Collections.shuffle(pool); // Shuffle the list for randomness
        return pool.subList(0, Math.min(5, pool.size())); // Return up to 5 quests
    }
}